[package]
name = "kami"
version = "0.1.0"
authors = ["Mike <mwalczyk2@gmail.com>"]
edition = "2018"

[lib]
name = "kami"
crate-type = ["lib"]

[dependencies]
approx = "0.3.2"
nalgebra-glm = "0.7.0"
num-traits = "0.2"
serde = { version = "1.0.114", features = ["derive"] }
serde_json = "1.0.56"